name: CI

on: [push]

jobs:
    ci:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]

        runs-on: ${{matrix.os}}

        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
              path: 'source'
              fetch-depth: 0
              lfs: 'false'

        - name: Cache Qt
          id: cache-qt
          uses: actions/cache@v1
          with:
              path: ../Qt
              key: ${{ runner.os }}-QtCache

        - name: Install Qt
          uses: jurplel/install-qt-action@v2
          with:
              cached: ${{ steps.cache-qt.outputs.cache-hit }}

        - name: Install OpenCascade[Ubuntu]
          if: startsWith(matrix.os, 'ubuntu')
          run: |
              sudo apt-get -y install libocct-data-exchange-dev libocct-draw-dev
              GH_CASCADE_INC_DIR=`dpkg -L libocct-foundation-dev | grep -i "Standard_Version.hxx" | sed "s/\/Standard_Version.hxx//i"`
              GH_CASCADE_LIB_DIR=`dpkg -L libocct-foundation-dev | grep -i "libTKernel.so" | sed "s/\/libTKernel.so//i"`
              echo "GH_CASCADE_INC_DIR=$GH_CASCADE_INC_DIR" >> $GITHUB_ENV
              echo "GH_CASCADE_LIB_DIR=$GH_CASCADE_LIB_DIR" >> $GITHUB_ENV

        - name: Install OpenCascade[macOS]
          if: startsWith(matrix.os, 'macos')
          run: |
              brew install opencascade
              GH_CASCADE_BASE_DIR=`brew --cellar opencascade`
              GH_CASCADE_VERSION=`brew info opencascade | grep -E --only-matching --max-count=1 "[0-9]\.[0-9]\.[0-9]"`
              echo "GH_CASCADE_INC_DIR=$GH_CASCADE_BASE_DIR/$GH_CASCADE_VERSION/include/opencascade" >> $GITHUB_ENV
              echo "GH_CASCADE_LIB_DIR=$GH_CASCADE_BASE_DIR/$GH_CASCADE_VERSION/lib" >> $GITHUB_ENV

        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Create Build folder
          run: mkdir ${{github.workspace}}/build

        - name: QMake
          working-directory: ${{github.workspace}}/build
          run: |
              echo CASCADE_INC_DIR=${{env.GH_CASCADE_INC_DIR}}
              echo CASCADE_LIB_DIR=${{env.GH_CASCADE_LIB_DIR}}
              qmake ../source  CASCADE_INC_DIR=${{env.GH_CASCADE_INC_DIR}}  CASCADE_LIB_DIR=${{env.GH_CASCADE_LIB_DIR}}  CONFIG+=withtests

        - name: Build
          working-directory: ${{github.workspace}}/build
          run: |
              make -j${{steps.cpu-cores.outputs.count}}

        - name: Execute Unit Tests[Ubuntu]
          if: startsWith(matrix.os, 'ubuntu')
          working-directory: ${{github.workspace}}/build
          env:
              DISPLAY: :0
          run: |
              Xvfb $DISPLAY -screen 0 1280x1024x24 &
              sleep 5s
              ./mayo --runtests

        - name: Execute Unit Tests[macOS]
          if: startsWith(matrix.os, 'macos')
          working-directory: ${{github.workspace}}/build
          run: |
              ./mayo.app/Contents/MacOS/mayo --runtests
